export const HOME='arnsui://app/welcome.html';
export function homeQuery(raw){
 try{const u=new URL(raw);if(u.protocol!=='arnsui:'||u.hostname!=='app'||u.port||u.username||u.password||u.pathname!=='/welcome.html'||u.hash||raw.length>2200)return null;
  if([...u.searchParams.keys()].some(k=>k!=='q')||u.searchParams.getAll('q').length>1)return null;
  const q=u.searchParams.get('q')||'';return q.length<=160?q:null;
 }catch{return null;}
}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s?new Date(s).toISOString().slice(0,16).replace('T',' ')+' UTC':'Not downloaded';
export function renderSearchHome(template,result){
 const r=result,items=r.hits.map(row=>`<article class="search-result"><p class="result-address">ar://${escape(row.name)}</p><h3><a href="ar://${escape(row.name)}">${escape(row.title||row.name)}</a></h3><p class="excerpt">${escape(row.excerpt)}</p><p class="availability">${row.localReady?'Saved on this device':row.availability==='prepared'?'Site copy reported by peer':'Entry page indexed · other files may be missing'}</p><p class="result-dates">Name observed: ${escape(date(row.observedAt))} · Page indexed: ${escape(date(row.indexedAt))}</p></article>`).join('');
 const search=`<form class="search-form" method="get" action="${HOME}" role="search"><label for="mesh-query">Search indexed ArNS sites</label><div class="search-input"><input id="mesh-query" name="q" type="search" maxlength="160" value="${escape(r.query)}" placeholder="Try music, news or a topic…" required><button type="submit">Search Mesh <span aria-hidden="true">↗</span></button></div><p>Search this device’s downloaded catalogue. Your search words stay on this device.</p></form>`;
 const results=`<section class="search-results" aria-labelledby="results-title"><div class="catalogue-head"><div><p class="eyebrow">MESH DISCOVERY · PREVIEW</p><h2 id="results-title">${r.query?`${r.total} result${r.total===1?'':'s'} for “${escape(r.query)}”`:'Discover more than a name.'}</h2></div><a class="refresh-catalogue" href="arnsui://app/search-refresh">${r.syncing?'Updating catalogue…':'Refresh catalogue'}</a></div><p class="catalogue-status">${r.entries} indexed site${r.entries===1?'':'s'} · ${r.sources} trusted publisher${r.sources===1?'':'s'} · Catalogue: ${escape(date(r.generatedAt))}</p>${!r.sources?'<p class="search-notice">No catalogue has been downloaded from a trusted publisher yet. <a href="arnsui://app/connect">Connect to a Mesh network</a>, then refresh the catalogue.</p>':''}${r.error?'<p class="search-notice">Catalogue update unavailable. Any previously accepted catalogue remains searchable.</p>':''}${r.query&&!r.total&&r.sources?'<p class="search-notice">No match in this catalogue. Try another word, or open a known ArNS name in the address bar. A missing result does not mean the site does not exist.</p>':''}${items}${r.total>30?'<p>Showing the first 30 results. Add another word to narrow your search.</p>':''}<p class="search-scope">Search covers a limited set of indexed entry pages. Dates and availability are reports from your trusted publisher. Opening a result checks the name and files again; missing files and external services may still prevent a complete page.</p></section>`;
 return template.replace('<body>',r.query?'<body class="searching">':'<body>').replace('<!-- MESH_SEARCH -->',search).replace('<!-- MESH_RESULTS -->',results);
}
