export const HOME='arnsui://app/welcome.html';
export function homeQuery(raw){
 try{const u=new URL(raw);if(u.protocol!=='arnsui:'||u.hostname!=='app'||u.port||u.username||u.password||u.pathname!=='/welcome.html'||u.hash||raw.length>2200)return null;
  if([...u.searchParams.keys()].some(k=>k!=='q')||u.searchParams.getAll('q').length>1)return null;
  const q=u.searchParams.get('q')||'';return q.length<=160?q:null;
 }catch{return null;}
}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s?new Date(s).toISOString().slice(0,16).replace('T',' ')+' UTC':'Not downloaded';
export function renderSearchHome(template,result){
 const r=result,topics=row=>(row.keywords||[]).map(tag=>`<a class="topic-tag" href="${HOME}?q=${escape(encodeURIComponent(tag))}">${escape(tag)}</a>`).join(''),items=r.hits.map(row=>`<article class="search-result"><p class="result-address">ar://${escape(row.name)}</p><h3><a href="ar://${escape(row.name)}">${escape(row.title||row.name)}</a></h3><p class="excerpt">${escape(row.excerpt)}</p>${row.keywords?.length?`<p class="result-topics" aria-label="Topics">${topics(row)}</p>`:''}<p class="availability">${row.localReady?'Saved on this device':row.availability==='prepared'?'Site copy reported by peer':row.availability==='metadata'?'ArNS listing · page availability checked when opened':'Entry page indexed · other files may be missing'}</p><p class="result-dates">Name observed: ${escape(date(row.observedAt))} · ${row.availability==='metadata'?'Listing updated':'Page indexed'}: ${escape(date(row.indexedAt))}</p></article>`).join('');
 const search=`<form class="search-form" method="get" action="${HOME}" role="search"><label class="sr-only" for="mesh-query">Search ArNS sites by topic or name</label><div class="search-input"><input id="mesh-query" name="q" type="search" maxlength="160" value="${escape(r.query)}" placeholder="Search a topic, keyword or ArNS name…" required><button type="submit">Search Mesh <span aria-hidden="true">↗</span></button></div></form><p class="search-hint">Discover ArNS sites by topic. Use the address bar above to open a site directly.</p>`;
 const refresh=`<a class="refresh-catalogue" href="arnsui://app/search-refresh">${r.syncing?'Updating catalogue…':'Refresh catalogue'}</a>`;
 const count=`<p class="catalogue-status">${r.entries} indexed site${r.entries===1?'':'s'}</p>`;
 const heading=r.query?`<div class="catalogue-head"><h2 id="results-title">${r.total} result${r.total===1?'':'s'} for “${escape(r.query)}”</h2>${refresh}</div>${count}`:`<div class="catalogue-summary">${count}${refresh}</div>`;
 const results=`<section class="search-results" ${r.query?'aria-labelledby="results-title"':'aria-label="Search catalogue"'}>${heading}${!r.sources?'<p class="search-notice"><a href="arnsui://app/connect">Connect to Mesh</a> to download a search catalogue.</p>':''}${r.error?'<p class="search-notice">Catalogue update unavailable. Any saved catalogue remains searchable.</p>':''}${r.query&&!r.total&&r.sources?'<p class="search-notice">No matching ArNS sites in this catalogue. Try a related word or the site’s language. You can also open a known name in the address bar.</p>':''}${items}${r.total>30?'<p class="result-limit">Showing the first 30 results. Add another word to narrow your search.</p>':''}<details class="catalogue-details"><summary>${r.query?'About these results':'Catalogue details'}</summary><p>${r.sources} trusted publisher${r.sources===1?'':'s'} · Catalogue: ${escape(date(r.generatedAt))}</p><p>Your search words stay on this device. Results match ArNS names, publisher descriptions and keywords, plus prepared page titles and text. Topics are supplied by site owners or pages, not endorsements. This catalogue has limited coverage; a missing result does not mean the site does not exist. Dates and availability are reports from your trusted publisher. Opening a result checks the name and files again; missing files and external services may still prevent a complete page.</p></details></section>`;
 return template.replace('<body>',r.query?'<body class="searching">':'<body>').replace('<!-- MESH_SEARCH -->',search).replace('<!-- MESH_RESULTS -->',results);
}
